### GENERAL SETTINGS ###

# Site settings
title: Roy Xue is Here :)
description: "Lazy Guy"
analytics: UA-58877422-1 
baseurl: "" #important: start with /
url: "http://royxue.me"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url: "https://www.facebook.com/roy.xue29"
  - title: twitter
    url: "https://twitter.com/xljroy"
  - title: instagram
    url: "http://instagram.com/xljroy"
  - title: tumblr
    url: 
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - FE2341,
    - 213E2B1,
    - Inside Memory.
email: xljroy@gmail.com
tel: uknown


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Kinda lazy guy, lol"

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lazy Guy"
    author: Roy Xue
    position: Lazy Hacker
